name: Build
on: push
jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Use Node.js Setup
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Build Electron App
        uses: tjmcraft/action-electron-builder@main
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          gh_token: ${{ secrets.github_token }}
          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
